# Generated by Django 3.1.7 on 2021-02-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UI', '0002_delete_extendeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phoneNumber', models.CharField(max_length=200, null=True)),
                ('cnic', models.CharField(max_length=200, null=True)),
                ('apiRequestStatus', models.CharField(default='Pending', max_length=200, null=True)),
            ],
        ),
    ]
